# Generated by Django 4.2.6 on 2023-11-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='image.jpg', upload_to=''),
        ),
    ]
